spring:
  datasource:
    url: jdbc:mysql://192.168.35.239:3306/chat
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: chat_server
    password: chat_server
  data:
    mongodb:
      host: 192.168.35.239
      port: 27017
      authentication-database: admin
      database: chat-server
      username: chat-server
      password: chat-server
