spring:
  datasource:
    url: jdbc:mysql://192.168.35.239:3306/chat?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  data:
    mongodb:
      host: 192.168.35.239
      port: 27017
      authentication-database: admin
      database: message
      username: root
      password: root
